### ISSUE TITLE
Crash on server start

### ISSUE THREAD

**Issue by OrdinatorStouff** [Tschipp/fakename#1]
Fresh install of Forge 2202 server and Fakename MC1.10.2 v1.0.jar -- No other mods installed

Crashlog: [Exception in server tick loop](http://pastebin.com/xvTbWXQN)

**Comment by Tschipp** [comment]
I will have a fix later today. Thanks for the report

**Comment by Tschipp** [comment]
Fixed it. You can re-download it here: [https://minecraft.curseforge.com/projects/fakename/files](url)
