### ISSUE TITLE
Aternos Server Crashes While Having Fakename Installed (Version 1.20.1)

### ISSUE THREAD

**Issue by Azrien27** [Tschipp/fakename#19]
Everytime I start the Aternos server, it just crashes immediately and it will not start. The only time that I can avoid crashing and to make it start again is to remove the Fakename Mod.

Analyzing the crash report, to potentially fix this issue, I would have to downgrade my Forge Version from 47.2.0 to 46-47.1.3 and that would actually mean downgrading to Minecraft 1.20 and I don't really wanna do that since if I were to do that, it will cause some complications with my other installed mods and it will crash again. Same result.

What do I need to do in order to avoid server crash? 

Running on Forge 47.2.0 (1.20.1)
Fakename is on Version 1.3.1

CRASH REPORT: https://mclo.gs/L2zZTur
LOG: https://mclo.gs/hbU7Hxu

![ATERNOS CRASH](https://github.com/Tschipp/fakename/assets/146932754/bb202228-d37c-4492-ac6e-6498a5b5936d)
![ATERNOS CRASH 2](https://github.com/Tschipp/fakename/assets/146932754/c9353273-78b4-41a3-8230-2485f5b36f30)

**Comment by matteo335** [comment]
Fakenames is a mod using a somewhat old version of Forge comaparing to other mods.
Currently your server is set for Forge 1.20.1 47.2.0, the required version for Fakenames to work is between **46 and 47.1.3**

Also note a lot/some devs do not help with Aternos as it's not a reliable hosting service - can have many ingame issues and cause problems that shouldn't occur.

**Comment by Tschipp** [comment]
Should be fixed with PR #24, which will be released soon
