### ISSUE TITLE
Not compatible with the latest version 1.20.1

### ISSUE THREAD

**Issue by cutekitticat** [Tschipp/fakename#22]
Fakename is not compatible with the latest forge version 47.2.20 in 1.20.1 !

**Comment by AqueleHaru** [comment]
same here. :/ waiting for an update

**Comment by cutekitticat** [comment]
Bro still not patching or responding, I hope he's not dead

**Comment by confect1ondev** [comment]
Hi, I had this issue last night as well. I was able to resolve it by changing [this line](https://github.com/Tschipp/fakename/blob/28eca3f0eaa454691314a909b7b1d53022dae863/src/main/resources/META-INF/mods.toml#L20C5-L20C31). Please note that it's not an official fix and you may run into unexpected issues. That said, I haven't run into any bugs not already in the Issues tab and it generally seems to work fine with later versions of Forge.

Edit: Looks like PR #24 and PR #25 are open to address this.
