### ISSUE TITLE
Fakename 1.12.1 error

### ISSUE THREAD

**Issue by LorenzoPapi** [Tschipp/fakename#3]
On curseforge, the mod for 1.12.2 shows a support or 1.12.1, but when I put that in my 1.12.1 forge server, it says that it requires 1.12.2.
Help?
Edit: I figured out what the problem is and teh solution, but you have to resolve it:
![Catqtura](https://user-images.githubusercontent.com/42911751/59495491-ab7bde00-8e8f-11e9-9083-c73a99bff82f.PNG)
The fact is that on the support version, you put 1.12.2 twice, probably a writing error

**Comment by Tschipp** [comment]
Why are you playing in 1.12.1 anyway??

**Comment by LorenzoPapi** [comment]
It was a test, but now I've switched to 1.12.2. Anyway it's a beautiful mod.
