### ISSUE TITLE
[suggestion] Allow option for non-op players to be able to change their own names, but not others'.

### ISSUE THREAD

**Issue by fuzzyweapon** [Tschipp/fakename#5]
As an operator, it's a bit of a pain to have to manage changing names when...
- any new player is onboarded
- every time any player wishes to change it
- every time any player screws up their formatting (colors or spaces)
- every time anyone wants to incorporate name changes into events, roleplaying, friendly immersive griefing, or whatever goofy reason.

This doesn't scale well, and some servers don't have to be proactive about functionally locking everything down, but instead favor reactive measures when server policies are broken.

Implementing this would make implementing #4 more impactful.

**Comment by Tschipp** [comment]
Added in 1.15
